#FROM confluentinc/cp-kafka-connect-base:6.0.1
FROM cnfldemos/cp-server-connect-datagen:0.4.0-6.0.1
RUN confluent-hub install --no-prompt debezium/debezium-connector-postgresql:1.3.1
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-elasticsearch:11.0.2

